/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppBreadcrumbs: typeof import('./src/components/common/AppBreadcrumbs.vue')['default']
    BlueBtn: typeof import('./src/components/common/BlueBtn.vue')['default']
    Categories: typeof import('./src/components/Categories.vue')['default']
    Footer: typeof import('./src/components/layouts/Footer.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    MainSlider: typeof import('./src/components/MainSlider.vue')['default']
    Navigation: typeof import('./src/components/Navigation/navigation.vue')['default']
    ProductCard: typeof import('./src/components/ProductCard.vue')['default']
    ProductCards: typeof import('./src/components/ProductCards.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Searchinput: typeof import('./src/components/Searchinput.vue')['default']
  }
}
